// import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Playfair_Display } from 'next/font/google'
import "./globals.css";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Head from 'next/head';
import Header from '@/components/Header';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const inter = Inter({ subsets: ['latin'] })
const playfair = Playfair_Display({ 
  subsets: ['latin'],
  variable: '--font-playfair'
})


export const metadata = {
  title: 'Astrolawrence',
  description: 'Get accurate astrological predictions and guidance from our expert astrologers.',
}

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${inter.className} ${playfair.variable} bg-light`}>
//         <Header/>
//         <Navbar />
//         {children}
//         <Footer/>
//       </body>
//     </html>
//   )
// }


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${playfair.variable} bg-light min-h-screen`}>
        <Header />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
